### ISSUE TITLE
Oops something failed....

### ISSUE THREAD

**Issue by RicoLouis24** [biuuu/genshin-wish-export#248]
![image](https://github.com/biuuu/genshin-wish-export/assets/163239947/273a80b5-b253-47b9-92da-d34117ae3f57)

请问这个问题如何解决？ 可以帮忙修复这个问题吗？ 今天抽了千織想要更新 就发生这样的问题了。。。 海砂帮忙修一修

**Comment by sugtao4423** [comment]
I have same issue.

<details>
<summary><code>userData\log.txt</code></summary>

```
[AUTHKEY_TIMEOUT][2024/3/13 16:08:00]false
[ERROR][2024/3/13 16:08:00]TypeError: Cannot read properties of undefined (reading 'find')
[AUTHKEY_TIMEOUT][2024/3/13 16:09:55]false
[ERROR][2024/3/13 16:09:55]TypeError: Cannot read properties of undefined (reading 'find')
[AUTHKEY_TIMEOUT][2024/3/13 16:10:29]false
[ERROR][2024/3/13 16:10:29]TypeError: Cannot read properties of undefined (reading 'find')
```

</details>

**Comment by biuuu** [comment]
点选项里的复制URL，看有没有内容。发给我邮箱 luna@css.moe 看看

**Comment by sugtao4423** [comment]
Yes, the URL exists.

Could be an error in the getItemTypeNameMap function.
The following is the content of the console.

```
TypeError: Cannot read properties of undefined (reading 'find')
    at D:\path\to\Genshin-Wish-Export\resources\app\dist\electron\main\main.js:26:9931
    at Array.forEach (<anonymous>)
    at dN (D:\path\to\Genshin-Wish-Export\resources\app\dist\electron\main\main.js:26:9909)
    at ng.getItemTypeNameMap (D:\path\to\Genshin-Wish-Export\resources\app\dist\electron\main\main.js:26:10015)
    at ex (D:\path\to\Genshin-Wish-Export\resources\app\dist\electron\main\main.js:101:8044)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\path\to\Genshin-Wish-Export\resources\app\dist\electron\main\main.js:101:8558
    at async node:electron/js2c/browser_init:197:563
```

**Comment by biuuu** [comment]
Try v0.11.3

**Comment by sugtao4423** [comment]
Thank you.
But v0.11.3 had the same error.

So I inserted debug code to verify.

<details>
<summary>Diff of debug code</summary>

```diff
diff --git a/src/main/gachaTypeMap.js b/src/main/gachaTypeMap.js
index 2e5bfda..415baf3 100644
--- a/src/main/gachaTypeMap.js
+++ b/src/main/gachaTypeMap.js
@@ -1,3 +1,4 @@
+const { sendMsg } = require('./utils')
 const itemTypeNameMap = require('../gachaType.json')
 
 const order = ['301', '302', '200', '500', '100']
@@ -14,5 +15,7 @@ function convertItemTypeMap(mapObject) {
 }
 
 exports.getItemTypeNameMap = function(lang) {
+  sendMsg('getItemTypeNameMap', 'DEBUG - func')
+  sendMsg(lang, 'DEBUG - lang')
   return convertItemTypeMap(itemTypeNameMap[lang])
 }
\ No newline at end of file
diff --git a/src/main/getData.js b/src/main/getData.js
index 9d9ad25..5f89a62 100644
--- a/src/main/getData.js
+++ b/src/main/getData.js
@@ -404,6 +404,7 @@ const fetchData = async (urlOverride) => {
     sendMsg(message)
     throw new Error(message)
   }
+  sendMsg(url, 'DEBUG - url')
   const searchParams = getQuerystring(url)
   if (!searchParams) {
     const message = text.url.incorrect
```

</details>

<details>
<summary>Debug log</summary>
The URL is processed.

```
[DEBUG - url][2024/3/13 17:43:49]https://hk4e-api-os.hoyoverse.com/gacha_info/api/getGachaLog?{SOME_PARAMS}&lang=ja&{SOME_PARAMS_INCLUDES_AUTHKEY}
[AUTHKEY_TIMEOUT][2024/3/13 17:43:50]false
[DEBUG - func][2024/3/13 17:43:50]getItemTypeNameMap
[DEBUG - lang][2024/3/13 17:43:50]ja
[ERROR][2024/3/13 17:43:50]TypeError: Cannot read properties of undefined (reading 'find')
```

</details>

It seems that the lang format has changed and I need to make sure for all languages.

**Comment by biuuu** [comment]
@sugtao4423 
`https://hk4e-api-os.hoyoverse.com/gacha_info/api/getGachaLog?{SOME_PARAMS}&lang=ja&{SOME_PARAMS_INCLUDES_AUTHKEY}`
When you replace “ja” with “ja-jp,” does the request still return data correctly?

**Comment by RicoLouis24** [comment]
> 点选项里的复制URL，看有没有内容。发给我邮箱 [luna@css.moe](mailto:luna@css.moe) 看看

可以了最新的版本  修好了
