### ISSUE TITLE
大佬，可以弄一个Mac版的工具吗？

### ISSUE THREAD

**Issue by CainLuo** [biuuu/genshin-wish-export#96]
大佬，可以弄一个Mac版的工具吗？

**Comment by Aniverse** [comment]
Mac 上连**官方**的原神客户端都没有……要么通过一些方法跑 iOS 版的，要么就是第三方的云游戏  
或许你可以试试网页版的非小酋

**Comment by leng-yue** [comment]
我刚刚搓了一个, 准备 pr 了

**Comment by leng-yue** [comment]
#97

**Comment by CainLuo** [comment]
> 我加上了 #97

好的，感谢大佬~

**Comment by CainLuo** [comment]
> 

原生客户端的确是没有，但是M1的机型可以通过一些手段装ipa，也算是一种原生客户端吧~

**Comment by drahnieR** [comment]
@leng-yue mac上还是用yarn来打包吗？我这边会报一个`esbuild.startService`函数不存在的错误
```
yarn run v1.22.10
$ node .electron-vite/dev-runner.js
         ___                      __                                                      __
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __   /\ \__      __
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\_\  \ \ ,_\   / ,.`\
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\/\ \  \ \ \/  /\  __/
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \ \  \ \ \_ \ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/_/   \ \__\ \/____/
                                     \/__/                                                   \/__/
getting ready...

TypeError: esbuild.startService is not a function
    at Object.buildStart (/Users/reinhard/ws/game/genshin-wish-export/node_modules/rollup-plugin-esbuild/dist/index.js:81:33)
    at /Users/reinhard/ws/game/genshin-wish-export/node_modules/rollup/dist/shared/rollup.js:22681:25
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 2)
    at async Object.rollupInternal (/Users/reinhard/ws/game/genshin-wish-export/node_modules/rollup/dist/shared/rollup.js:23397:9)
    at async Task.run (/Users/reinhard/ws/game/genshin-wish-export/node_modules/rollup/dist/shared/watch.js:238:22)
    at async Watcher.run (/Users/reinhard/ws/game/genshin-wish-export/node_modules/rollup/dist/shared/watch.js:170:13) {
  code: 'PLUGIN_ERROR',
  plugin: 'esbuild',
  hook: 'buildStart'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by biuuu** [comment]
@drahnieR 
https://github.com/leng-yue/genshin-wish-export/actions/
You can directly download the built application in the github actions of length-yue/genshin-wish-export .
If building the app yourself, make sure to use the code from https://github.com/leng-yue/genshin-wish-export .

**Comment by drahnieR** [comment]
package from https://github.com/leng-yue/genshin-wish-export/actions/ won't open, says it's not compatible.

I was able to build this myself with some dependency changes, but there's no window on open. Not sure if it's an electron issue as I've seen this on other projects as well.

```diff
diff --git a/package.json b/package.json
index 574061f..757626c 100644
--- a/package.json
+++ b/package.json
@@ -68,7 +68,6 @@
       "icon": "build/icons"
     }
   },
-  "dependencies": {},
   "devDependencies": {
     "@rollup/plugin-alias": "^3.1.2",
     "@rollup/plugin-commonjs": "^17.1.0",
@@ -77,7 +76,7 @@
     "@types/electron-devtools-installer": "^2.2.0",
     "@types/node": "^14.14.31",
     "@vitejs/plugin-vue": "1.1.5",
-    "@vue/compiler-sfc": "^3.0.7",
+    "@vue/compiler-sfc": "3.1.x",
     "adm-zip": "^0.5.3",
     "autoprefixer": "^10.2.4",
     "cfonts": "^2.9.1",
@@ -92,6 +91,7 @@
     "electron-unhandled": "^3.0.2",
     "electron-window-state": "^5.0.3",
     "element-plus": "^1.0.2-beta.33",
+    "esbuild": "^0.8.x",
     "fs-extra": "^9.1.0",
     "get-stream": "^6.0.0",
     "lodash-es": "^4.17.21",
@@ -100,6 +100,7 @@
     "ora": "^5.3.0",
     "portfinder": "^1.0.28",
     "postcss": "^8.2.6",
+    "rollup": "^2.66.1",
     "rollup-plugin-esbuild": "^2.6.1",
     "semver": "^7.3.4",
     "tailwindcss": "^2.0.3",
```

**Comment by leng-yue** [comment]
What device are you using? I tested on the M1 Pro device.

**Comment by drahnieR** [comment]
I'm not on M1, MBP 13-inch, 2018, with macOS 12.2

**Comment by leng-yue** [comment]
Can you send me a screenshot of the incompatible error?

**Comment by drahnieR** [comment]
@leng-yue here you go
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1078578/154036918-1b07ae50-bf02-419c-a35e-c3ef37585a08.png">
also, this is how the app's icon look like
<img width="113" alt="image" src="https://user-images.githubusercontent.com/1078578/154037106-fb1551c8-cabe-4f68-9393-a2a1e8327287.png">

**Comment by leng-yue** [comment]
Sorry about that. I found the issue and will fix it today.

**Comment by yozoo** [comment]
macOS也能用，这是我去年4月编译的。

![genshin](https://user-images.githubusercontent.com/13715640/154829640-a01396ef-3835-4f16-bad6-8c4c32f95ce0.png)
